-- Run this complete file once in the existing Tripti Supabase SQL Editor.
-- These upgrades assume the original setup.sql has already been applied.
begin;
-- Tripti Jewellers commerce upgrade
-- Run this file in Supabase SQL Editor only when the local changes are ready to go live.

create sequence if not exists public.invoice_number_seq start with 1001;

alter table public.orders add column if not exists payment_status text not null default 'pending';
alter table public.orders add column if not exists payment_provider text not null default '';
alter table public.orders add column if not exists provider_order_id text;
alter table public.orders add column if not exists provider_payment_id text;
alter table public.orders add column if not exists paid_at timestamptz;
alter table public.orders add column if not exists invoice_number text;
alter table public.orders add column if not exists shipping_city text not null default '';
alter table public.orders add column if not exists shipping_state text not null default '';
alter table public.orders add column if not exists shipping_pincode text not null default '';
alter table public.orders add column if not exists shipping_provider text not null default '';
alter table public.orders add column if not exists shipping_order_id text;
alter table public.orders add column if not exists shipment_id text;
alter table public.orders add column if not exists awb_code text;
alter table public.orders add column if not exists tracking_url text;
alter table public.orders add column if not exists shipping_status text not null default 'not_created';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'orders_payment_status_check' and conrelid = 'public.orders'::regclass
  ) then
    alter table public.orders add constraint orders_payment_status_check
      check (payment_status in ('pending', 'created', 'paid', 'cod_pending', 'failed', 'refunded'));
  end if;
end;
$$;

create unique index if not exists idx_orders_invoice_number on public.orders(invoice_number) where invoice_number is not null;
create unique index if not exists idx_orders_provider_order_id on public.orders(provider_order_id) where provider_order_id is not null;

create or replace function public.assign_invoice_number()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.invoice_number is null or trim(new.invoice_number) = '' then
    new.invoice_number := 'TJI-' || to_char(timezone('Asia/Kolkata', now()), 'YYYY') || '-' || lpad(nextval('public.invoice_number_seq')::text, 6, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists assign_order_invoice_number on public.orders;
create trigger assign_order_invoice_number
before insert on public.orders
for each row execute procedure public.assign_invoice_number();

update public.orders
set invoice_number = 'TJI-' || to_char(timezone('Asia/Kolkata', created_at), 'YYYY') || '-' || lpad(nextval('public.invoice_number_seq')::text, 6, '0')
where invoice_number is null;

create table if not exists public.cart_items (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  size text not null default '',
  quantity integer not null default 1 check (quantity between 1 and 10),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, product_id, size)
);

create table if not exists public.contact_messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  name text not null,
  email text not null,
  phone text not null,
  message text not null,
  status text not null default 'new' check (status in ('new', 'in_progress', 'resolved', 'spam')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.notification_log (
  id bigint generated by default as identity primary key,
  order_id uuid references public.orders(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  channel text not null check (channel in ('email', 'sms', 'shipping')),
  event text not null,
  status text not null check (status in ('sent', 'failed', 'skipped')),
  provider_id text not null default '',
  error_message text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  unique (order_id, channel, event)
);

drop trigger if exists set_cart_items_updated_at on public.cart_items;
create trigger set_cart_items_updated_at before update on public.cart_items
for each row execute procedure public.set_updated_at();

drop trigger if exists set_contact_messages_updated_at on public.contact_messages;
create trigger set_contact_messages_updated_at before update on public.contact_messages
for each row execute procedure public.set_updated_at();

alter table public.cart_items enable row level security;
alter table public.contact_messages enable row level security;
alter table public.notification_log enable row level security;

drop policy if exists "cart_items_own" on public.cart_items;
create policy "cart_items_own" on public.cart_items for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "contact_messages_admin" on public.contact_messages;
create policy "contact_messages_admin" on public.contact_messages for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "notification_log_own_or_admin" on public.notification_log;
create policy "notification_log_own_or_admin" on public.notification_log for select to authenticated
using ((select auth.uid()) = user_id or (select public.is_admin()));

revoke all on public.cart_items, public.contact_messages, public.notification_log from anon, authenticated;
grant select, insert, update, delete on public.cart_items to authenticated;
grant select, update, delete on public.contact_messages to authenticated;
grant select on public.notification_log to authenticated;
grant usage, select on sequence public.notification_log_id_seq to authenticated;

create or replace function public.replace_cart(p_items jsonb)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_item jsonb;
  v_count integer := 0;
  v_product_id bigint;
  v_quantity integer;
  v_size text;
begin
  if v_user_id is null then
    raise exception 'Please sign in before syncing your bag.';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'Shopping bag data is invalid.';
  end if;

  delete from public.cart_items where user_id = v_user_id;
  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_product_id := (v_item ->> 'id')::bigint;
    v_quantity := greatest(1, least(10, coalesce((v_item ->> 'quantity')::integer, 1)));
    v_size := coalesce(v_item ->> 'size', '');
    if exists (select 1 from public.products where id = v_product_id and is_active = true) then
      insert into public.cart_items (user_id, product_id, size, quantity)
      values (v_user_id, v_product_id, v_size, v_quantity)
      on conflict (user_id, product_id, size)
      do update set quantity = excluded.quantity, updated_at = timezone('utc', now());
      v_count := v_count + 1;
    end if;
  end loop;
  return v_count;
end;
$$;

revoke all on function public.replace_cart(jsonb) from public;
grant execute on function public.replace_cart(jsonb) to authenticated;

create or replace function public.place_order_v2(
  p_customer_name text,
  p_phone text,
  p_address text,
  p_city text,
  p_state text,
  p_pincode text,
  p_payment_method text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_order_id uuid := gen_random_uuid();
  v_order_number text := 'TJ-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
  v_email text;
  v_subtotal integer := 0;
  v_shipping integer := 0;
  v_free_shipping integer := 999;
  v_standard_shipping integer := 79;
  v_item jsonb;
  v_product public.products%rowtype;
  v_quantity integer;
  v_size text;
  v_invoice_number text;
begin
  if v_user_id is null then raise exception 'Please sign in before placing an order.'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'Your shopping bag is empty.'; end if;
  if length(trim(coalesce(p_customer_name, ''))) < 2 then raise exception 'Enter the customer name.'; end if;
  if length(regexp_replace(coalesce(p_phone, ''), '[^0-9]', '', 'g')) < 10 then raise exception 'Enter a valid phone number.'; end if;
  if length(trim(coalesce(p_address, ''))) < 8 or length(trim(coalesce(p_city, ''))) < 2 or length(trim(coalesce(p_state, ''))) < 2 then
    raise exception 'Enter the complete delivery address.';
  end if;
  if trim(coalesce(p_pincode, '')) !~ '^[0-9]{6}$' then raise exception 'Enter a valid 6-digit PIN code.'; end if;
  if lower(trim(coalesce(p_payment_method, ''))) not in ('razorpay', 'cash on delivery') then raise exception 'Choose a valid payment method.'; end if;

  select email into v_email from public.profiles where id = v_user_id;
  if v_email is null then raise exception 'Customer profile was not found.'; end if;

  insert into public.orders (
    id, order_number, user_id, customer_name, email, phone, address,
    shipping_city, shipping_state, shipping_pincode, payment_method,
    payment_provider, payment_status
  ) values (
    v_order_id, v_order_number, v_user_id, trim(p_customer_name), v_email, trim(p_phone), trim(p_address),
    trim(p_city), trim(p_state), trim(p_pincode), trim(p_payment_method),
    case when lower(p_payment_method) = 'razorpay' then 'razorpay' else '' end,
    case when lower(p_payment_method) = 'cash on delivery' then 'cod_pending' else 'pending' end
  );

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := greatest(1, least(10, coalesce((v_item ->> 'quantity')::integer, 1)));
    v_size := coalesce(v_item ->> 'size', '');
    select * into v_product from public.products
    where id = (v_item ->> 'id')::bigint and is_active = true for update;
    if not found then raise exception 'A product in your bag is no longer available.'; end if;
    if v_product.stock < v_quantity then raise exception 'Not enough stock for %.', v_product.name; end if;
    v_subtotal := v_subtotal + (v_product.price * v_quantity);
    insert into public.order_items (order_id, product_id, product_name, price, quantity, size)
    values (v_order_id, v_product.id, v_product.name, v_product.price, v_quantity, v_size);
    update public.products set stock = stock - v_quantity where id = v_product.id;
  end loop;

  select free_shipping_minimum, standard_shipping into v_free_shipping, v_standard_shipping
  from public.site_settings where id = 1;
  v_shipping := case when v_subtotal >= coalesce(v_free_shipping, 999) then 0 else coalesce(v_standard_shipping, 79) end;
  update public.orders set subtotal = v_subtotal, shipping = v_shipping, total = v_subtotal + v_shipping where id = v_order_id;
  select invoice_number into v_invoice_number from public.orders where id = v_order_id;
  return jsonb_build_object(
    'id', v_order_id,
    'order_number', v_order_number,
    'invoice_number', v_invoice_number,
    'subtotal', v_subtotal,
    'shipping', v_shipping,
    'total', v_subtotal + v_shipping,
    'payment_method', p_payment_method
  );
end;
$$;

revoke all on function public.place_order_v2(text, text, text, text, text, text, text, jsonb) from public;
grant execute on function public.place_order_v2(text, text, text, text, text, text, text, jsonb) to authenticated;

-- Footer, information pages, stores and delivery areas.
-- Apply only when the owner asks to activate the changes online.
create table if not exists public.site_content (
  id text primary key check (id = 'main'),
  content jsonb not null check (jsonb_typeof(content) = 'object'),
  updated_at timestamptz not null default now()
);
alter table public.site_content enable row level security;
drop policy if exists "site_content_public_read" on public.site_content;
create policy "site_content_public_read" on public.site_content for select to anon, authenticated using (true);
drop policy if exists "site_content_admin_write" on public.site_content;
create policy "site_content_admin_write" on public.site_content for all to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));
revoke all on public.site_content from anon, authenticated;
grant select on public.site_content to anon;
grant select, insert, update, delete on public.site_content to authenticated;
drop trigger if exists site_content_updated_at on public.site_content;
create trigger site_content_updated_at before update on public.site_content
for each row execute procedure public.set_updated_at();

-- Apply after commerce-upgrade.sql. Prices and coupon eligibility are server-authoritative.
create table if not exists public.coupons (
 id uuid primary key default gen_random_uuid(),
 code text not null unique check (code ~ '^[A-Z0-9_-]{3,32}$'),
 title text not null default '',
 discount_type text not null check (discount_type in ('flat','percent')),
 value integer not null check (value > 0),
 min_subtotal integer not null default 0 check (min_subtotal >= 0),
 max_discount integer check (max_discount > 0),
 excluded_categories text[] not null default '{}',
 starts_at timestamptz,
 expires_at timestamptz,
 active boolean not null default true,
 created_at timestamptz not null default now(),
 check (discount_type <> 'percent' or value <= 100),
 check (expires_at is null or starts_at is null or expires_at > starts_at)
);
alter table public.coupons enable row level security;
drop policy if exists coupons_public_read on public.coupons;
create policy coupons_public_read on public.coupons for select to anon, authenticated
 using (active and (starts_at is null or starts_at<=now()) and (expires_at is null or expires_at>now()));
drop policy if exists coupons_admin on public.coupons;
create policy coupons_admin on public.coupons for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
revoke all on public.coupons from anon,authenticated;
grant select on public.coupons to anon;
grant select,insert,update,delete on public.coupons to authenticated;
alter table public.orders add column if not exists coupon_code text;
alter table public.orders add column if not exists discount integer not null default 0 check (discount>=0);

create or replace function public.quote_coupon(p_code text,p_items jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare
 c public.coupons%rowtype; item jsonb; product public.products%rowtype;
 subtotal bigint:=0; eligible bigint:=0; qty integer; amount bigint;
begin
 if p_items is null or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 or jsonb_array_length(p_items)>100 then raise exception 'Your shopping bag is empty or invalid.'; end if;
 select * into c from public.coupons where code=upper(trim(p_code)) for share;
 if not found or not c.active then raise exception 'This coupon is not available.'; end if;
 if c.starts_at>now() then raise exception 'This coupon has not started yet.'; end if;
 if c.expires_at<=now() then raise exception 'This coupon has expired.'; end if;
 for item in select value from jsonb_array_elements(p_items) loop
  qty:=(item->>'quantity')::integer;
  if qty is null or qty<1 or qty>10 then raise exception 'Invalid product quantity.'; end if;
  select * into product from public.products where id=(item->>'id')::bigint and is_active;
  if not found then raise exception 'A product in your bag is unavailable.'; end if;
  subtotal:=subtotal+product.price::bigint*qty;
  if not exists(select 1 from unnest(c.excluded_categories) category where lower(category)=lower(product.category)) then eligible:=eligible+product.price::bigint*qty; end if;
 end loop;
 if subtotal<c.min_subtotal then raise exception 'Minimum order value for this coupon is Rs. %.',c.min_subtotal; end if;
 if eligible<=0 then raise exception 'This coupon does not apply to the products in your bag.'; end if;
 amount:=case when c.discount_type='percent' then floor(eligible*c.value/100.0)::bigint else c.value end;
 amount:=least(eligible,amount,coalesce(c.max_discount,amount));
 if amount<1 then raise exception 'This coupon cannot discount this order.'; end if;
 return jsonb_build_object('code',c.code,'title',c.title,'subtotal',subtotal,'discount',amount,'excluded_categories',c.excluded_categories);
end; $$;
revoke all on function public.quote_coupon(text,jsonb) from public;
grant execute on function public.quote_coupon(text,jsonb) to anon,authenticated;

create or replace function public.place_order_v3(p_customer_name text,p_phone text,p_address text,p_city text,p_state text,p_pincode text,p_payment_method text,p_items jsonb,p_coupon_code text default '')
returns jsonb language plpgsql security definer set search_path='' as $$
declare result jsonb; quoted jsonb; order_id uuid; amount integer:=0;
begin
 if auth.uid() is null then raise exception 'Please sign in before placing an order.'; end if;
 -- v2 locks product rows and snapshots their current prices within this transaction.
 result:=public.place_order_v2(p_customer_name,p_phone,p_address,p_city,p_state,p_pincode,p_payment_method,p_items);
 order_id:=(result->>'id')::uuid;
 if trim(coalesce(p_coupon_code,''))<>'' then
  quoted:=public.quote_coupon(p_coupon_code,p_items);
  amount:=(quoted->>'discount')::integer;
  update public.orders set discount=amount,coupon_code=quoted->>'code',total=subtotal+shipping-amount where id=order_id;
 end if;
 return result||jsonb_build_object('discount',amount,'coupon_code',quoted->>'code','total',(result->>'total')::integer-amount);
end; $$;
revoke all on function public.place_order_v3(text,text,text,text,text,text,text,jsonb,text) from public;
grant execute on function public.place_order_v3(text,text,text,text,text,text,text,jsonb,text) to authenticated;


commit;

