(function () {
  "use strict";
  async function initialize() {
    const service = window.TriptiContent;
    let content = structuredClone(await service.load());
    const esc = service.esc;
    const nav = document.querySelector(".admin-sidebar nav");
    const button=document.createElement("button");button.type="button";button.dataset.adminPanel="site-details";button.textContent="⌖ Footer & locations";nav.append(button);
    const panel=document.createElement("section");panel.className="admin-panel";panel.id="admin-panel-site-details";panel.hidden=true;
    panel.innerHTML=`<div class="admin-section-heading"><div><p class="eyebrow">Customer information</p><h2>Footer, pages & locations</h2></div><a class="button button-outline" href="stores.html" target="_blank" rel="noopener">Preview store finder</a></div>
      <p class="content-edit-note">${service.isLocal?"Local preview: changes saved here appear on this browser’s local website. Your live website stays unchanged. Export a backup before publishing.":"Changes saved here appear on your website."} Empty phone, social and app links stay hidden until you fill them in.</p>
      <div class="content-admin-tabs" role="group" aria-label="Content sections"><button type="button" data-content-tab="details" class="is-active">Footer details</button><button type="button" data-content-tab="pages">Information pages</button><button type="button" data-content-tab="stores">Stores & map pins</button><button type="button" data-content-tab="delivery">Delivery PIN codes</button></div>
      <p id="content-save-status" class="form-status" role="status" hidden></p>
      <section data-content-section="details"><form id="footer-details-form" class="admin-form"><h3>Brand & contact</h3><div id="footer-detail-fields" class="form-row"></div><h3>Social & app links</h3><div id="footer-link-fields" class="form-row"></div><button class="button button-gold" type="submit">Save footer details</button></form></section>
      <section data-content-section="pages" hidden><form id="information-editor" class="admin-form"><h3>Edit information pages</h3><label for="content-page-select">Choose page</label><select id="content-page-select"></select><label for="content-page-title">Page title</label><input id="content-page-title" required maxlength="100"><label for="content-page-body">Page content</label><textarea id="content-page-body" rows="13" required></textarea><p class="form-note">Use a blank line between paragraphs. Review policy text for your business before publishing.</p><div class="form-actions"><button class="button button-gold" type="submit">Save page</button><a id="content-page-preview" class="button button-outline" target="_blank" rel="noopener">Preview page</a></div></form></section>
      <section data-content-section="stores" hidden><div class="admin-editor-layout"><form id="store-editor" class="admin-form"><h3 id="store-editor-title">Add a store</h3><input name="id" type="hidden"><label>Store name<input name="name" required maxlength="120"></label><label>Street address<textarea name="address" required rows="3"></textarea></label><div class="form-row"><label>City<input name="city" required></label><label>State<input name="state" required></label><label>PIN code<input name="pincode" pattern="[1-9][0-9]{5}" inputmode="numeric" maxlength="6" required></label><label>Store phone<input name="phone" type="tel"></label></div><label>Opening hours<input name="hours" placeholder="e.g. Monday–Saturday, 10 AM–7 PM"></label><label>Google Maps link<input name="mapUrl" type="url" placeholder="https://maps.google.com/…"></label><div class="form-row"><label>Latitude<input name="lat" type="number" step="any" min="-90" max="90"></label><label>Longitude<input name="lng" type="number" step="any" min="-180" max="180"></label></div><p class="form-note">Map coordinates enable nearest-store detection. Right-click the store’s pin in Google Maps to copy latitude and longitude.</p><label class="checkbox-single"><input name="active" type="checkbox" checked> Show this store</label><div class="form-actions"><button class="button button-gold" type="submit">Save store</button><button class="button button-outline" type="button" id="reset-store-editor">New store</button></div></form><div id="content-store-list" class="content-record-list"></div></div></section>
      <section data-content-section="delivery" hidden><div class="admin-editor-layout"><form id="zone-editor" class="admin-form"><h3>Delivery coverage</h3><input name="id" type="hidden"><label>Area name<input name="name" placeholder="e.g. Local delivery" required></label><label>PIN code or prefix<input name="prefix" inputmode="numeric" pattern="[1-9][0-9]{1,5}" minlength="2" maxlength="6" placeholder="e.g. 110001 or 110" required></label><p class="form-note">A full PIN code takes priority over a shorter prefix. Only add areas your delivery service actually covers.</p><div class="form-row"><label>Minimum working days<input name="minDays" type="number" min="1" max="90" value="4" required></label><label>Maximum working days<input name="maxDays" type="number" min="1" max="90" value="8" required></label></div><label>Delivery note<textarea name="note" rows="3"></textarea></label><label class="checkbox-single"><input name="available" type="checkbox" checked> Delivery available</label><label class="checkbox-single"><input name="cod" type="checkbox"> Cash on delivery available</label><div class="form-actions"><button class="button button-gold" type="submit">Save delivery area</button><button id="reset-zone-editor" type="button" class="button button-outline">New area</button></div></form><div id="content-zone-list" class="content-record-list"></div></div></section>
      <div class="content-backup"><button class="button button-outline" id="export-content" type="button">Export details backup</button><label class="button button-outline">Import details backup<input id="import-content" type="file" accept="application/json,.json" class="sr-only"></label></div>`;
    document.querySelector("#admin-main").append(panel);
    const status=panel.querySelector("#content-save-status");
    function report(text,error=false){status.textContent=text;status.dataset.type=error?"error":"success";status.hidden=false;}
    async function persist(next){content=structuredClone(await service.save(next));report(service.isLocal?"Saved in local preview. Refresh the local website to see your changes.":"Website details saved.");}
    const details=[["brand","Brand name"],["tagline","Brand tagline"],["phone","Contact phone"],["whatsapp","WhatsApp number with country code"],["email","Contact email"],["hours","Contact opening hours"],["copyright","Copyright text"],["paymentNote","Payment options text"],["locatorTitle","Store finder heading"],["locatorIntro","Store finder introduction"],["deliveryNote","Delivery estimate note"]];
    const links=[["instagram","Instagram"],["facebook","Facebook"],["youtube","YouTube"],["x","X / Twitter"],["playStore","Play Store app link"],["appStore","App Store app link"]];
    function fillFields(){panel.querySelector("#footer-detail-fields").innerHTML=details.map(([key,label])=>`<label>${label}<input name="${key}" value="${esc(content[key])}" type="${key==="email"?"email":"text"}" ${["brand","email"].includes(key)?"required":""}></label>`).join("");panel.querySelector("#footer-link-fields").innerHTML=links.map(([key,label])=>`<label>${label}<input name="${key}" type="url" value="${esc(content[key])}" placeholder="https://…"></label>`).join("");}
    panel.querySelectorAll("[data-content-tab]").forEach(tab=>tab.addEventListener("click",()=>{panel.querySelectorAll("[data-content-section]").forEach(s=>s.hidden=s.dataset.contentSection!==tab.dataset.contentTab);panel.querySelectorAll("[data-content-tab]").forEach(t=>t.classList.toggle("is-active",t===tab));status.hidden=true;}));
    async function submit(form,operation){const b=form.querySelector('[type="submit"]');b.disabled=true;try{await operation();}catch(e){report(e.message,true);}finally{b.disabled=false;}}
    panel.querySelector("#footer-details-form").addEventListener("submit",e=>{e.preventDefault();submit(e.currentTarget,async()=>{const values=new FormData(e.target);const next=structuredClone(content);[...details,...links].forEach(([key])=>next[key]=String(values.get(key)||"").trim());for(const [key] of links){if(next[key]&&!service.safeUrl(next[key]))throw new Error("Use an http or https URL for social and app links.");}await persist(next);});});
    const selector=panel.querySelector("#content-page-select");
    function fillPage(){const p=content.pages.find(p=>p.slug===selector.value);if(!p)return;panel.querySelector("#content-page-title").value=p.title;panel.querySelector("#content-page-body").value=p.body;panel.querySelector("#content-page-preview").href=`information.html?page=${encodeURIComponent(p.slug)}`;}
    function pageOptions(){const old=selector.value;selector.innerHTML=content.pages.map(p=>`<option value="${esc(p.slug)}">${esc(p.title)}</option>`).join("");if(content.pages.some(p=>p.slug===old))selector.value=old;fillPage();}
    selector.addEventListener("change",fillPage);
    panel.querySelector("#information-editor").addEventListener("submit",e=>{e.preventDefault();submit(e.currentTarget,async()=>{const next=structuredClone(content);const p=next.pages.find(p=>p.slug===selector.value);p.title=panel.querySelector("#content-page-title").value.trim();p.body=panel.querySelector("#content-page-body").value.trim();await persist(next);pageOptions();});});
    function renderRecords(){
      panel.querySelector("#content-store-list").innerHTML=content.stores.length?content.stores.map(s=>`<article><span class="eyebrow">${s.active?"Visible":"Hidden"}</span><h3>${esc(s.name)}</h3><p>${esc(s.address)}, ${esc(s.city)} · ${esc(s.pincode)}</p><div class="table-actions"><button type="button" data-edit-store="${esc(s.id)}">Edit</button><button type="button" data-remove-store="${esc(s.id)}">Remove</button></div></article>`).join(""):'<div class="content-empty-note"><h3>Your stores belong here</h3><p>Add your first store with its address and map pin. City cards and store counts are calculated automatically.</p></div>';
      panel.querySelector("#content-zone-list").innerHTML=content.zones.length?content.zones.map(z=>`<article><span class="eyebrow">PIN ${esc(z.prefix)}${z.prefix.length<6?"…":""}</span><h3>${esc(z.name)}</h3><p>${z.available?`${z.minDays}–${z.maxDays} working days`:"Unavailable"}</p><div class="table-actions"><button type="button" data-edit-zone="${esc(z.id)}">Edit</button><button type="button" data-remove-zone="${esc(z.id)}">Remove</button></div></article>`).join(""):'<div class="content-empty-note"><h3>Add your delivery areas</h3><p>Customers can check these PIN codes from the product page or delivery page.</p></div>';
    }
    function resetEditor(kind){panel.querySelector(`#${kind}-editor`).reset();panel.querySelector(`#${kind}-editor`).elements.id.value="";}
    ["store","zone"].forEach(kind=>{
      const form=panel.querySelector(`#${kind}-editor`), key=kind==="store"?"stores":"zones";
      panel.querySelector(`#reset-${kind}-editor`).addEventListener("click",()=>resetEditor(kind));
      form.addEventListener("submit",e=>{e.preventDefault();submit(form,async()=>{
        const fields=Object.fromEntries(new FormData(form));const item={...fields,id:fields.id||crypto.randomUUID()};
        if(kind==="store"){
          item.active=form.elements.active.checked;
          if(Boolean(fields.lat)!==Boolean(fields.lng))throw new Error("Enter both latitude and longitude, or leave both empty.");
          item.lat=fields.lat===""?"":Number(fields.lat);item.lng=fields.lng===""?"":Number(fields.lng);
          if(item.mapUrl&&!service.safeUrl(item.mapUrl))throw new Error("Use an http or https Maps link.");
        } else {
          item.available=form.elements.available.checked;item.cod=form.elements.cod.checked;item.minDays=Number(fields.minDays);item.maxDays=Number(fields.maxDays);
          if(item.maxDays<item.minDays)throw new Error("Maximum delivery days must be at least the minimum.");
          if(content.zones.some(z=>z.prefix===item.prefix&&z.id!==item.id))throw new Error("This PIN code or prefix already exists. Edit its current entry.");
        }
        const next=structuredClone(content);const index=next[key].findIndex(s=>s.id===item.id);if(index<0)next[key].push(item);else next[key][index]=item;
        await persist(next);resetEditor(kind);renderRecords();
      });});
    });
    panel.addEventListener("click",async e=>{
      for(const kind of ["store","zone"]){
        const edit=e.target.closest(`[data-edit-${kind}]`),remove=e.target.closest(`[data-remove-${kind}]`),key=kind==="store"?"stores":"zones";
        if(edit){const item=content[key].find(s=>s.id===edit.getAttribute(`data-edit-${kind}`));const form=panel.querySelector(`#${kind}-editor`);Object.entries(item).forEach(([k,v])=>{const field=form.elements.namedItem(k);if(field){if(field.type==="checkbox")field.checked=!!v;else field.value=v??"";}});form.scrollIntoView({behavior:"smooth",block:"start"});}
        if(remove&&confirm(`Remove this ${kind==="store"?"store":"delivery area"}?`)){try{const next=structuredClone(content);next[key]=next[key].filter(s=>s.id!==remove.getAttribute(`data-remove-${kind}`));await persist(next);renderRecords();}catch(error){report(error.message,true);}}
      }
    });
    panel.querySelector("#export-content").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(content,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="tripti-website-details.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
    panel.querySelector("#import-content").addEventListener("change",async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw new Error("Please choose a backup smaller than 1 MB.");const incoming=JSON.parse(await file.text());if(typeof incoming.brand!=="string"||!Array.isArray(incoming.pages)||!Array.isArray(incoming.stores)||!Array.isArray(incoming.zones))throw new Error("This is not a Tripti details backup.");if(!confirm("Replace the current footer, pages and locations with this backup?"))return;await persist(incoming);fillFields();pageOptions();renderRecords();}catch(error){report(error.message,true);}finally{e.target.value="";}});
    fillFields();pageOptions();renderRecords();
  }
  window.TriptiContentAdmin={initialize};
})();
