(function(){
 'use strict';
 async function initialize(){
  const api=window.TriptiSupabase,esc=window.TriptiContent.esc;let coupons=[];
  const button=document.createElement('button');button.type='button';button.dataset.adminPanel='coupons';button.textContent='％ Coupons';document.querySelector('.admin-sidebar nav').append(button);
  const panel=document.createElement('section');panel.className='admin-panel';panel.id='admin-panel-coupons';panel.hidden=true;
  panel.innerHTML=`<div class="admin-section-heading"><div><p class="eyebrow">Offers & promotions</p><h2>Coupon codes</h2></div></div><p id="coupon-admin-status" class="form-status" role="status" hidden></p><div class="admin-editor-layout"><form id="coupon-editor" class="admin-form"><h3>Create or edit coupon</h3><input name="id" type="hidden"><label>Coupon code<input name="code" pattern="[A-Za-z0-9_-]{3,32}" maxlength="32" placeholder="e.g. WELCOME500" required></label><label>Offer description<input name="title" maxlength="200" placeholder="e.g. Welcome offer on your jewellery order"></label><div class="form-row"><label>Discount type<select name="discount_type"><option value="flat">Fixed amount (₹)</option><option value="percent">Percentage (%)</option></select></label><label>Discount value<input name="value" type="number" min="1" step="1" required></label><label>Minimum order (₹)<input name="min_subtotal" type="number" min="0" step="1" value="0" required></label><label>Maximum discount (₹), optional<input name="max_discount" type="number" min="1" step="1"></label></div><label>Excluded categories (comma-separated)<input name="excluded_categories" placeholder="Coins, Idols, Gift Cards"></label><div class="form-row"><label>Starts at (your local time)<input name="starts_at" type="datetime-local"></label><label>Expires at (your local time)<input name="expires_at" type="datetime-local"></label></div><label class="checkbox-single"><input name="active" type="checkbox" checked> Coupon active</label><p class="form-note">Active offers appear in the bag. Discounts are checked again when an order is placed.</p><div class="form-actions"><button type="submit" class="button button-gold">Save coupon</button><button id="reset-coupon" type="button" class="button button-outline">New coupon</button></div></form><div id="coupon-records" class="content-record-list"></div></div>`;
  document.querySelector('#admin-main').append(panel);const form=panel.querySelector('form'),status=panel.querySelector('[role="status"]'),list=panel.querySelector('#coupon-records');
  function report(text,error=false){status.textContent=text;status.dataset.type=error?'error':'success';status.hidden=false;}
  function reset(){form.reset();form.elements.id.value='';}
  async function refresh(){try{coupons=await api.select('coupons','select=*&order=created_at.desc');list.innerHTML=coupons.length?coupons.map(c=>`<article><p class="eyebrow">${c.active?'Active':'Disabled'}</p><h3>${esc(c.code)}</h3><p>${esc(c.title)}</p><p>${c.discount_type==='percent'?c.value+'%':'₹'+c.value} off · minimum ₹${c.min_subtotal}</p>${c.expires_at?`<p>Ends ${esc(new Date(c.expires_at).toLocaleString())}</p>`:''}<div class="table-actions"><button type="button" data-edit-coupon="${c.id}">Edit</button><button type="button" data-toggle-coupon="${c.id}">${c.active?'Disable':'Enable'}</button></div></article>`).join(''):'<p>No coupons yet. Create your first offer.</p>';}catch(e){list.textContent='Coupon database setup is required before coupons can be saved.';}}
  panel.querySelector('#reset-coupon').onclick=reset;
  form.addEventListener('submit',async e=>{e.preventDefault();const b=form.querySelector('[type="submit"]');b.disabled=true;try{const v=Object.fromEntries(new FormData(form));const payload={code:v.code.trim().toUpperCase(),title:v.title.trim(),discount_type:v.discount_type,value:Number(v.value),min_subtotal:Number(v.min_subtotal),max_discount:v.max_discount?Number(v.max_discount):null,excluded_categories:v.excluded_categories.split(',').map(x=>x.trim()).filter(Boolean),starts_at:v.starts_at?new Date(v.starts_at).toISOString():null,expires_at:v.expires_at?new Date(v.expires_at).toISOString():null,active:form.elements.active.checked};if(payload.discount_type==='percent'&&payload.value>100)throw new Error('Percentage cannot exceed 100.');if(payload.expires_at&&payload.starts_at&&payload.expires_at<=payload.starts_at)throw new Error('Expiry must be after the start.');if(v.id)await api.update('coupons',payload,`id=eq.${encodeURIComponent(v.id)}`);else await api.insert('coupons',payload);report('Coupon saved. Eligible customers can apply it in their bag.');reset();await refresh();}catch(error){report(error.status===404?'Activate the coupon database setup first.':error.message,true);}finally{b.disabled=false;}});
  list.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit-coupon]'),toggle=e.target.closest('[data-toggle-coupon]');if(edit){const c=coupons.find(c=>c.id===edit.dataset.editCoupon);Object.entries(c).forEach(([key,value])=>{const field=form.elements.namedItem(key);if(!field)return;if(key==='active')field.checked=value;else if(key==='excluded_categories')field.value=value.join(', ');else if(['starts_at','expires_at'].includes(key)){const d=value?new Date(value):null;field.value=d?new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16):'';}else field.value=value??'';});form.scrollIntoView({behavior:'smooth'});}if(toggle){toggle.disabled=true;try{const c=coupons.find(c=>c.id===toggle.dataset.toggleCoupon);await api.update('coupons',{active:!c.active},`id=eq.${c.id}`);await refresh();report('Coupon updated.');}catch(error){report(error.message,true);toggle.disabled=false;}}});
  await refresh();
 }
 window.TriptiCouponAdmin={initialize};
})();
