(function(){
 'use strict';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const safe=v=>{try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}};
 const eligible=o=>['pending','confirmed','processing'].includes(o.status);
 async function customers(orders,container){
  let services=[],ready=true;
  try{services=await window.TriptiSupabase.select('order_service','select=*');}catch{ready=false;}
  for(const [index,o] of orders.entries()){
   const card=container.querySelectorAll('.order-card')[index];if(!card)continue;
   const s=services.find(x=>x.order_id===o.id)||{};const url=safe(s.tracking_url||o.tracking_url);
   const box=document.createElement('section');box.className='order-service';
   const stages=['pending','confirmed','processing','shipped','delivered'],at=stages.indexOf(o.status);
   box.innerHTML=`<h3>Track your order</h3>${o.status==='cancelled'?'<p>Order cancelled</p>':`<ol class="order-progress">${stages.map((stage,i)=>`<li class="${i===at?'current':''}">${i===at?'● ':''}${stage}${i===at?' — current status':''}</li>`).join('')}</ol>`}<p>${esc(s.tracking_note||'Tracking updates will be added by our team.')}</p>${s.courier?`<p>Courier: ${esc(s.courier)} · Tracking ID: ${esc(s.awb||'Pending')}</p>`:''}${url?`<a class="text-link" href="${esc(url)}" target="_blank" rel="noopener">Track on courier website ↗</a>`:''}${s.updated_at?`<small>Details updated: ${esc(new Date(s.updated_at).toLocaleString())}</small>`:''}${s.cancel_status?`<div class="cancel-request"><strong>Cancellation ${esc(s.cancel_status)}</strong><p>Reason: ${esc(s.cancel_reason)}</p><p>${esc(s.cancel_reply||'Our team will review your request. Your order is not cancelled yet.')}</p>${s.cancel_status==='approved'?'<p>Refund, if applicable, is handled separately. Approval does not confirm a completed refund.</p>':''}</div>`:eligible(o)?`<details><summary>Request cancellation</summary><form><label>Cancellation reason<select name="reason" required><option value="">Choose a reason</option><option>Ordered by mistake</option><option>Want to change the design or size</option><option>Delivery taking too long</option><option>Changed my mind</option><option>Other</option></select></label><label>Additional details<textarea name="note" maxlength="700"></textarea></label><p>This sends a request for review; it does not instantly cancel or refund the order.</p><button class="button button-outline" ${ready?'':'disabled'}>Submit cancellation request</button><p role="status">${ready?'':'Cancellation service is awaiting activation. Please contact support.'}</p></form></details>`:'<p>For help with a dispatched or completed order, <a href="contact.html">contact support</a>.</p>'}`;
   card.append(box);const form=box.querySelector('form');if(form)form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button'),status=form.querySelector('[role=status]');b.disabled=true;try{if(form.elements.reason.value==='Other'&&form.elements.note.value.trim().length<3)throw new Error('Please explain your reason.');await window.TriptiSupabase.rpc('request_order_cancellation',{p_order:o.id,p_reason:[form.elements.reason.value,form.elements.note.value.trim()].filter(Boolean).join(': ')});status.textContent='Cancellation request saved. Refresh this page to see its status.';}catch(err){status.textContent=err.message;b.disabled=false;}};
  }
 }
 async function initializeAdmin(){
  const api=window.TriptiSupabase,b=document.createElement('button');b.type='button';b.dataset.adminPanel='fulfilment';b.textContent='Tracking & cancellations';document.querySelector('.admin-sidebar nav').append(b);
  const panel=document.createElement('section');panel.className='admin-panel';panel.id='admin-panel-fulfilment';panel.hidden=true;panel.innerHTML='<h2>Tracking & cancellations</h2><p>Update shipment details here. Order stage is managed in Orders. Verify courier cancellation before approving; refunds and stock adjustments must be handled separately.</p><p role="status"></p><div class="service-records"></div>';document.querySelector('#admin-main').append(panel);
  async function refresh(){try{const [orders,services]=await Promise.all([api.select('orders','select=id,order_number,status&order=created_at.desc'),api.select('order_service','select=*')]);panel.querySelector('.service-records').innerHTML=orders.map(o=>{const s=services.find(x=>x.order_id===o.id)||{};return `<form class="admin-form order-service" data-order="${o.id}"><h3>${esc(o.order_number)} · ${esc(o.status)}</h3>${s.cancel_status?`<p>Cancellation: ${esc(s.cancel_status)} — ${esc(s.cancel_reason)}</p>`:''}<label>Courier<input name="courier" maxlength="100" value="${esc(s.courier)}"></label><label>Tracking ID<input name="awb" maxlength="100" value="${esc(s.awb)}"></label><label>HTTPS tracking link<input name="url" type="url" value="${esc(s.tracking_url)}"></label><label>Customer-facing tracking update<textarea name="note" maxlength="1000">${esc(s.tracking_note)}</textarea></label>${s.cancel_status==='requested'?'<label>Cancellation decision<select name="decision"><option value="">Keep pending</option><option value="approved">Approve cancellation</option><option value="rejected">Reject cancellation</option></select></label><label>Decision reason / refund instructions<textarea name="reply" maxlength="1000"></textarea></label>':''}<button class="button button-gold">Save update</button><p role="status"></p></form>`;}).join('')||'<p>No orders yet.</p>';}catch{panel.querySelector('[role=status]').textContent='Run supabase/order-service-upgrade.sql to activate tracking and cancellation management.';}}
  panel.onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('button'),v=Object.fromEntries(new FormData(f));if(v.url&&!safe(v.url)){f.querySelector('[role=status]').textContent='Enter a valid HTTPS tracking URL.';return;}if(v.decision&&(!v.reply||v.reply.trim().length<3)){f.querySelector('[role=status]').textContent='Please enter a decision reason (at least 3 characters).';return;}if(v.decision==='approved'&&!confirm('Cancel this order? Confirm courier cancellation first. This will NOT refund payment or restore inventory.'))return;b.disabled=true;try{await api.rpc('manage_order_service',{p_order:f.dataset.order,p_courier:v.courier,p_awb:v.awb,p_url:v.url,p_note:v.note,p_decision:v.decision||'',p_reply:v.reply||''});await refresh();panel.querySelector('[role=status]').textContent=v.decision==='approved'?'Order successfully cancelled. Refund and stock adjustments must be handled separately.':v.decision==='rejected'?'Cancellation request rejected.':'Tracking update saved.';}catch(err){f.querySelector('[role=status]').textContent=err.message;b.disabled=false;}};await refresh();
 }
 window.TriptiOrderService={customers,initializeAdmin,safe,eligible};
})();
