(function(){
 'use strict';
 if(new URLSearchParams(location.search).get('mode')==='reset')return;
 const emailForm=document.querySelector('#auth-form'),switcher=document.querySelector('.auth-mode-switcher');
 const box=document.createElement('section');box.className='phone-auth';
 box.innerHTML='<h2>Login / Create account</h2><p>Verify your mobile number to access your personal account.</p><form><label>Mobile number (+91)<input name="phone" type="tel" inputmode="numeric" pattern="[6-9][0-9]{9}" maxlength="10" autocomplete="tel-national" placeholder="10-digit mobile number" required></label><div class="otp-step" hidden><label>Verification code<input name="otp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6"></label></div><button class="button button-gold button-full" type="submit">Request OTP</button><button type="button" class="auth-text-button" data-resend hidden>Resend OTP</button><button type="button" class="auth-text-button" data-change hidden>Change number</button><p role="status"></p></form><p class="form-note">New customers receive an account after verification. Existing email accounts remain separate unless linked securely.</p>';
 emailForm.before(box);emailForm.hidden=true;if(switcher)switcher.hidden=true;
 const toggle=document.createElement('button');toggle.type='button';toggle.className='auth-text-button';toggle.textContent='Use email instead';box.after(toggle);
 toggle.onclick=()=>{const phoneVisible=!box.hidden;box.hidden=phoneVisible;emailForm.hidden=!phoneVisible;if(switcher)switcher.hidden=!phoneVisible;toggle.textContent=phoneVisible?'Use mobile OTP instead':'Use email instead';};
 const form=box.querySelector('form'),status=box.querySelector('[role=status]'),submit=form.querySelector('[type=submit]'),resend=box.querySelector('[data-resend]'),change=box.querySelector('[data-change]');let phone='',until=0,busy=false;
 function cooldown(){const remaining=Math.max(0,Math.ceil((until-Date.now())/1000));resend.disabled=busy||remaining>0;resend.textContent=remaining?`Resend in ${remaining}s`:'Resend OTP';}
 async function send(){const next='+91'+form.elements.phone.value.trim();await window.TriptiSupabase.requestPhoneOtp(next);phone=next;until=Date.now()+60000;form.elements.phone.readOnly=true;box.querySelector('.otp-step').hidden=false;form.elements.otp.required=true;submit.textContent='Verify & continue';resend.hidden=false;change.hidden=false;status.textContent='OTP requested. Check your SMS.';form.elements.otp.focus();cooldown();}
 async function work(fn){if(busy)return;busy=true;submit.disabled=true;change.disabled=true;resend.disabled=true;try{await fn();}catch(e){status.textContent=/provider|disabled|unsupported/i.test(e.message)?'Mobile OTP is awaiting SMS-provider activation. Please use email login for now.':e.message;}finally{busy=false;submit.disabled=false;change.disabled=false;cooldown();}}
 form.onsubmit=e=>{e.preventDefault();work(async()=>{if(!phone)return send();await window.TriptiSupabase.verifyPhoneOtp(phone,form.elements.otp.value.trim());const target=new URLSearchParams(location.search).get('returnTo')||'account.html';location.replace(/^[a-z0-9_-]+\.html(?:\?[a-z0-9_=&%-]*)?$/i.test(target)?target:'account.html');});};
 resend.onclick=()=>{if(Date.now()>=until)work(send);};change.onclick=()=>{phone='';form.elements.phone.readOnly=false;form.elements.otp.value='';form.elements.otp.required=false;box.querySelector('.otp-step').hidden=true;resend.hidden=true;change.hidden=true;submit.textContent='Request OTP';status.textContent='';};setInterval(cooldown,1000);
})();
