/* Store tools use Supabase authorization; customer data is never trusted locally. */
(function () {
 'use strict';
 const api=window.TriptiSupabase;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(v||0));
 const date=v=>new Date(v).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST';
 const statusHTML='<p role="status" aria-live="polite"></p>';
 function message(error){return /404|does not exist|schema cache|Could not find/i.test(error?.message||'')?'Store tools need database activation. Please contact the store; admin must run store-tools-upgrade.sql.':error?.message||'Could not save. Please try again.';}
 function card(title){const s=document.createElement('section');s.className='dashboard-card store-tools';s.innerHTML=`<h2>${esc(title)}</h2>${statusHTML}`;return s;}
 function bind(form,handler){form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const b=form.querySelector('button[type="submit"]'),s=form.querySelector('[role="status"]');b.disabled=true;s.textContent='Saving…';try{await handler(Object.fromEntries(new FormData(form)),form);s.textContent='Saved successfully.';}catch(err){s.textContent=message(err);}finally{b.disabled=false;}});}
 function photoField(publicPhoto=false){return `<label>Photo (optional, JPG/PNG/WebP, max 5 MB)<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"></label><small>${publicPhoto?'Your review, display name and photo will be public. Do not include personal information.':'Photo is visible only to you and store admins.'}</small>`;}
 function photoExtension(file){const types={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};if(!types[file.type]||file.size>5242880||!file.size)throw new Error('Choose a JPG, PNG or WebP image under 5 MB.');return types[file.type];}
 async function uploadPhoto(file,bucket,user){if(!file?.size)return '';const extension=photoExtension(file);const path=`${user.id}/${crypto.randomUUID()}.${extension}`;await api.uploadCustomerPhoto(bucket,path,file);return path;}
 function publicPhoto(path){if(!/^[a-f0-9-]+\/[a-f0-9-]+\.(jpg|png|webp)$/.test(path||''))return '';return `${api.config.url}/storage/v1/object/public/review-photos/${path}`;}
 function consentForm(){return `<form><label class="tool-check"><input type="checkbox" name="order_email"> Email me order status updates</label><label class="tool-check"><input type="checkbox" name="order_whatsapp"> I agree to receive order updates on my order's WhatsApp number</label><label class="tool-check"><input type="checkbox" name="cart_reminders"> Email me a reminder if I leave items in my bag</label><p>Cart reminders: after 24 hours, at most once in 7 days. Uncheck and save here anytime to stop future reminders. Delivery requires the store's messaging service to be active.</p><button type="submit" class="button button-gold">Save preferences</button>${statusHTML}</form>`;}
 async function preferences(host,user){
  const s=card('Notification preferences');s.id='notification-preferences';s.insertAdjacentHTML('beforeend',consentForm());host.append(s);
  const form=s.querySelector('form');form.querySelector('button').disabled=true;
  try{const rows=await api.select('customer_preferences',`select=*&user_id=eq.${user.id}`);const prefs=rows[0]||{order_email:true};for(const k of ['order_email','order_whatsapp','cart_reminders'])form.elements[k].checked=!!prefs[k];form.querySelector('button').disabled=false;}catch(e){s.querySelector('[role=status]').textContent=message(e);return;}
  bind(form,async()=>{await api.insert('customer_preferences',{user_id:user.id,...Object.fromEntries(['order_email','order_whatsapp','cart_reminders'].map(k=>[k,form.elements[k].checked])),updated_at:new Date().toISOString()},{upsert:true,onConflict:'user_id'});});
 }
 async function appointments(host,user){
  const s=card('Book an appointment');s.id='appointments';host.append(s);
  s.insertAdjacentHTML('beforeend',`<p>Request a store visit, video shopping session or custom jewellery consultation. Your time is tentative until the store confirms it.</p><form><label>Appointment type<select name="kind"><option>Store visit</option><option>Video shopping</option><option>Custom jewellery</option></select></label><label>Preferred date and time (your device's local time)<input type="datetime-local" name="time" required></label><label>Contact number (country code + digits, no spaces)<input type="tel" name="phone" minlength="10" maxlength="16" required></label><label>What would you like help with?<textarea name="note" maxlength="1000"></textarea></label><button type="submit" class="button button-gold">Request appointment</button>${statusHTML}</form><div class="tool-records"></div>`);
  async function list(){const rows=await api.select('appointments',`select=*&user_id=eq.${user.id}&order=created_at.desc&limit=100`);s.querySelector('.tool-records').innerHTML=rows.map(r=>`<article><h3>${esc(r.kind)}</h3><p>${esc(date(r.requested_at))} · ${esc(r.status)}</p><p>${esc(r.admin_note||'Awaiting store confirmation.')}</p></article>`).join('')||'<p>No appointments yet.</p>';}
  bind(s.querySelector('form'),async(v,f)=>{await api.rpc('book_appointment',{p_kind:v.kind,p_time:new Date(v.time).toISOString(),p_phone:v.phone,p_note:v.note});f.reset();await list();});
  try{await list();}catch(e){s.querySelector('[role=status]').textContent=message(e);}
 }
 async function customerOrders(host,user){
  const s=card('Returns, exchanges & verified reviews');host.append(s);
  try{
   const [orders,requests,reviews]=await Promise.all([api.select('orders',`select=id,order_number,status,order_items(id,product_id,product_name)&user_id=eq.${user.id}&status=eq.delivered&order=created_at.desc&limit=200`),api.select('aftercare_requests',`select=*&user_id=eq.${user.id}&order=created_at.desc&limit=200`),api.select('product_reviews',`select=product_id&user_id=eq.${user.id}`)]);
   s.insertAdjacentHTML('beforeend','<p>Requests are reviewed by the store. Approval does not itself issue a refund, ship an exchange or restore returned stock.</p>');
   for(const o of orders)for(const i of o.order_items){
    const d=document.createElement('article');d.className='tool-order';d.innerHTML=`<h3>${esc(i.product_name)}</h3><p>${esc(o.order_number)} · Delivered</p>`;s.append(d);
    const existing=requests.filter(r=>r.order_item_id===i.id);
    d.insertAdjacentHTML('beforeend',existing.map(r=>`<p><strong>${esc(r.kind)}: ${esc(r.status)}</strong> — ${esc(r.reason)}<br>${esc(r.admin_note)}</p>`).join(''));
    const kinds=existing.length?[]:['return','exchange'];
    if(kinds.length){d.insertAdjacentHTML('beforeend',`<details><summary>Request return / exchange</summary><form data-aftercare><label>Request type<select name="kind">${kinds.map(k=>`<option>${k}</option>`).join('')}</select></label><label>Reason<textarea name="reason" minlength="3" maxlength="1000" required></textarea></label>${photoField()}<button type="submit" class="button button-outline">Send request</button>${statusHTML}</form></details>`);
     bind(d.querySelector('[data-aftercare]'),async(v,f)=>{const path=await uploadPhoto(v.photo,'return-evidence',user);await api.rpc('submit_aftercare',{p_item:i.id,p_kind:v.kind,p_reason:v.reason,p_photo:path});f.reset();f.querySelector('button').hidden=true;});}
    if(i.product_id&&!reviews.some(r=>r.product_id===i.product_id)){d.insertAdjacentHTML('beforeend',`<details><summary>Write a verified purchase review</summary><form data-review><label>Public display name<input name="name" maxlength="40" required></label><label>Rating<select name="rating">${[5,4,3,2,1].map(n=>`<option value="${n}">${n} / 5</option>`).join('')}</select></label><label>Review<textarea name="review" minlength="3" maxlength="1500" required></textarea></label>${photoField(true)}<button type="submit" class="button button-outline">Publish review</button>${statusHTML}</form></details>`);
     bind(d.querySelector('[data-review]'),async(v,f)=>{const path=await uploadPhoto(v.photo,'review-photos',user);await api.rpc('submit_review',{p_item:i.id,p_rating:Number(v.rating),p_name:v.name,p_review:v.review,p_photo:path});f.reset();f.querySelector('button').hidden=true;});}
   }
   if(!orders.length)s.insertAdjacentHTML('beforeend','<p>Your delivered purchases will appear here.</p>');
  }catch(e){s.querySelector('[role=status]').textContent=message(e);}
 }
 async function customer(){const user=await api.getUser(),host=document.querySelector('#account-dashboard');if(!user||!host)return;await Promise.all([preferences(host,user),appointments(host,user),customerOrders(host,user)]);}
 async function product(){const id=Number(new URLSearchParams(location.search).get('id'));if(!id)return;const host=document.querySelector('#product-detail');if(!host)return;const s=card('Verified customer reviews');host.after(s);try{const rows=await api.rpc('read_product_reviews',{p_product:id});s.insertAdjacentHTML('beforeend',rows.length?rows.map(r=>`<article><strong>${esc(r.display_name)} · ${Number(r.rating)} / 5</strong><small>Verified purchase</small><p>${esc(r.review)}</p>${publicPhoto(r.photo_path)?`<img class="review-photo" loading="lazy" src="${esc(publicPhoto(r.photo_path))}" alt="Customer jewellery photo">`:''}</article>`).join(''):'<p>No reviews yet. Review your delivered purchase from <a href="account.html">My account</a>.</p>');}catch(e){s.querySelector('[role=status]').textContent=message(e);}}
 async function cart(){const host=document.querySelector('#main-content');if(!host)return;const user=await api.getUser();if(user)await preferences(host,user);else{const s=card('Save your bag');s.insertAdjacentHTML('beforeend','<p><a href="login.html?returnTo=cart.html">Sign in</a> to save your bag and choose optional email reminders.</p>');host.append(s);}}
 function adminPanel(name,title){const b=document.createElement('button');b.type='button';b.dataset.adminPanel=name;b.textContent=title;document.querySelector('.admin-sidebar nav').append(b);const s=card(title);s.id='admin-panel-'+name;s.classList.add('admin-panel');s.hidden=true;document.querySelector('#admin-main').append(s);return s;}
 async function stockPanel(){const s=adminPanel('inventory','Stock & low-stock alerts');s.insertAdjacentHTML('beforeend',`<p>Orders reserve stock during checkout. After database activation, cancellation restores it once. Cancelled orders cannot be reopened. Check returned goods before manually adjusting their stock.</p><button type="button" data-refresh class="button button-outline">Refresh stock</button><div class="tool-records"></div>`);
  async function load(){try{const rows=await api.rpc('low_stock_products',{});document.querySelector('[data-admin-panel="inventory"]').textContent=`Stock alerts (${rows.length})`;s.querySelector('.tool-records').innerHTML=rows.map(r=>`<form data-product="${r.id}"><h3>${esc(r.name)}</h3><p>${r.stock===0?'Out of stock':'Low stock'}: ${r.stock}</p><label>Alert when stock is at or below<input name="threshold" type="number" min="0" max="100000" value="${r.low_stock_threshold}" required></label><button type="submit" class="button button-outline">Save threshold</button>${statusHTML}</form>`).join('')||'<p>No low-stock products.</p>';s.querySelectorAll('form').forEach(f=>bind(f,async v=>{await api.update('products',{low_stock_threshold:Number(v.threshold)},`id=eq.${Number(f.dataset.product)}`);await load();}));}catch(e){s.querySelector('[role=status]').textContent=message(e);}}
  s.querySelector('[data-refresh]').onclick=load;await load();
 }
 async function requestPanel(){const s=adminPanel('aftercare','Returns & exchanges');s.insertAdjacentHTML('beforeend',`<p>Approval is a service decision only. Refunds, pickup, replacement shipment and returned-stock inspection must be handled separately.</p><button type="button" class="button button-outline" data-refresh>Refresh requests</button><div class="tool-records"></div>`);
  async function load(){try{const rows=await api.select('aftercare_requests','select=*,order_items(product_name,orders(order_number,customer_name))&order=created_at.desc&limit=200');s.querySelector('.tool-records').innerHTML=rows.map(r=>`<article><h3>${esc(r.order_items?.orders?.order_number)} · ${esc(r.kind)} · ${esc(r.status)}</h3><p>${esc(r.order_items?.orders?.customer_name)} — ${esc(r.order_items?.product_name)}</p><p>${esc(r.reason)}</p><p>${esc(r.admin_note)}</p>${r.photo_path?`<button type="button" data-photo="${esc(r.photo_path)}">View private evidence</button>`:''}${decisionForm(r,'aftercare')}</article>`).join('')||'<p>No return / exchange requests.</p>';wireDecisions(s,load);s.querySelectorAll('[data-photo]').forEach(b=>b.onclick=async()=>{try{const url=await api.customerPhotoURL('return-evidence',b.dataset.photo);const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.textContent='Open photo (link expires in 5 minutes)';b.replaceWith(a);}catch(e){s.querySelector('[role=status]').textContent=message(e);}});}catch(e){s.querySelector('[role=status]').textContent=message(e);}}
  s.querySelector('[data-refresh]').onclick=load;await load();
 }
 function decisionForm(r,type){const options=type==='aftercare'?(r.status==='requested'?['approved','rejected']:r.status==='approved'?['completed']:[]):(r.status==='requested'?['confirmed','cancelled']:r.status==='confirmed'?['completed','cancelled']:[]);return options.length?`<form data-request="${r.id}" data-type="${type}"><label>Decision<select name="status">${options.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Customer-facing instructions<textarea name="note" minlength="3" maxlength="1000" required></textarea></label><button type="submit" class="button button-gold">Save decision</button>${statusHTML}</form>`:'';}
 function wireDecisions(s,load){s.querySelectorAll('[data-request]').forEach(f=>bind(f,async v=>{if(!confirm('Save this decision? This does not transfer money or ship any items.'))throw new Error('No change made.');await api.rpc('manage_store_request',{p_type:f.dataset.type,p_id:f.dataset.request,p_status:v.status,p_note:v.note});await load();}));}
 async function engagementPanel(){const s=adminPanel('engagement','Appointments & notifications');s.insertAdjacentHTML('beforeend',`<p>Notifications remain queued until a delivery provider and scheduler are connected. “Sent” means accepted by the delivery service, not proof of delivery.</p><button type="button" class="button button-outline" data-refresh>Refresh</button> <button type="button" class="button button-gold" data-dispatch>Process pending notifications</button><h3>Appointments (latest 200)</h3><div data-appointments></div><h3>Notification queue (latest 100)</h3><div data-outbox></div>`);
  async function load(){try{const [a,n]=await Promise.all([api.select('appointments','select=*&order=created_at.desc&limit=200'),api.select('store_outbox','select=id,event,channel,status,attempts,last_error,created_at&order=created_at.desc&limit=100')]);s.querySelector('[data-appointments]').innerHTML=a.map(r=>`<article><h3>${esc(r.kind)} · ${esc(r.status)}</h3><p>${esc(date(r.requested_at))} · ${esc(r.phone)}</p><p>${esc(r.note)} ${esc(r.admin_note)}</p>${decisionForm(r,'appointment')}</article>`).join('')||'<p>No appointments yet.</p>';s.querySelector('[data-outbox]').innerHTML=n.map(r=>`<p>#${r.id} ${esc(r.event)} · ${esc(r.channel)} · <strong>${esc(r.status)}</strong> (${r.attempts} attempts)<br>${esc(r.last_error)}</p>`).join('')||'<p>No notification events yet.</p>';wireDecisions(s,load);}catch(e){s.querySelector('[role=status]').textContent=message(e);}}
  s.querySelector('[data-refresh]').onclick=load;s.querySelector('[data-dispatch]').onclick=async e=>{e.target.disabled=true;try{const session=await api.getSession();const res=await fetch('/api/store-notifications',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`}});const payload=await res.json();if(!res.ok)throw new Error(payload.error||'Notification processing failed');s.querySelector('[role=status]').textContent=`Processed ${payload.processed} notifications. Check the queue for delivery-service status.`;await load();}catch(err){s.querySelector('[role=status]').textContent=message(err);}finally{e.target.disabled=false;}};await load();
 }
 async function reportsPanel(){const s=adminPanel('sales-reports','Sales reports');s.insertAdjacentHTML('beforeend',`<p>Gross order value includes confirmed, processing, shipped and delivered orders. Pending and cancelled orders are excluded. This is not payment-received or net-of-refunds revenue. Dates use India time.</p><form><label>From<input name="from" type="date" required></label><label>Through<input name="to" type="date" required></label><button type="submit" class="button button-gold">Show report</button>${statusHTML}</form><div data-report></div>`);const f=s.querySelector('form');f.elements.from.value=new Date().toISOString().slice(0,7)+'-01';f.elements.to.value=new Date().toISOString().slice(0,10);
  async function load(v){const r=await api.rpc('store_sales_report',{p_from:v.from,p_to:v.to});s.querySelector('[data-report]').innerHTML=`<h3>${money(r.total)} gross order value · ${r.orders} orders</h3><p>${r.pending} pending orders (all dates)</p><h3>Daily</h3>${reportTable(r.daily,'day')}<h3>Monthly</h3>${reportTable(r.monthly,'month')}<h3>Best-selling products</h3>${(r.products||[]).map(p=>`<p>${esc(p.name)} — ${p.units} units · ${money(p.total)}</p>`).join('')||'<p>No sales in this period.</p>'}`;}
  bind(f,load);try{await load({from:f.elements.from.value,to:f.elements.to.value});}catch(e){s.querySelector('[role=status]').textContent=message(e);}
 }
 function reportTable(rows,key){return `<div class="tool-table"><table><thead><tr><th>Period</th><th>Orders</th><th>Gross order value</th></tr></thead><tbody>${(rows||[]).map(r=>`<tr><td>${esc(r[key])}</td><td>${r.orders}</td><td>${money(r.total)}</td></tr>`).join('')}</tbody></table></div>`;}
 async function admin(){await Promise.all([stockPanel(),requestPanel(),engagementPanel(),reportsPanel()]);}
 window.TriptiStoreTools={customer,product,cart,admin,photoExtension,publicPhoto,decisionForm};
})();
