const {test}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'js/shop-carousel.js'),'utf8');
function harness(width=1200){
 const events={},controls={},track={children:[],style:{},addEventListener(){},querySelectorAll(){return []},offsetWidth:100};
 Object.defineProperty(track,'innerHTML',{set(html){this.children=Array.from({length:(html.match(/<article /g)||[]).length},()=>({inert:false,setAttribute(){},querySelector(){return {}},getBoundingClientRect(){return {width:300}}}));}});
 const viewport={addEventListener(){}};
 const section={querySelector(s){if(s==='.shop-carousel-track')return track;if(s==='.shop-carousel-viewport')return viewport;return controls[s]??=( {setAttribute(){}} );}};
 const context={URL,console,innerWidth:width,matchMedia:()=>({matches:false}),setInterval(fn){events.tick=fn;return 1},clearInterval(){},setTimeout(fn){events.reset=fn;return 2},clearTimeout(){},document:{readyState:'loading',hidden:false,addEventListener(){},querySelector:()=>section},window:{addEventListener(){},TriptiSupabase:{select:async()=>[]}}};
 vm.createContext(context);vm.runInContext(source,context);return {api:context.window.TriptiShopCarousel,events,controls,track,context};
}
test('ten distinct optimized image assets and category destinations',()=>{const {api}=harness();const cards=api.defaults();assert.equal(cards.length,10);assert.equal(new Set(cards.map(x=>x.image_url)).size,10);for(const c of cards){assert.ok(fs.statSync(path.join(root,c.image_url)).size<500000);assert.ok(api.safe(c.link_url));}});
test('saved hide and content override defaults without changing RLS visibility',()=>{const {api}=harness();const cards=api.merge([{id:8,button_label:'shop-carousel:01',title:'New title',body:JSON.stringify({version:1,description:'Updated',enabled:false}),is_active:true,image_url:'javascript:bad',display_order:20}]);const card=cards.find(c=>c.slot===1);assert.equal(card.is_active,false);assert.equal(card.body,'Updated');assert.equal(card.title,'New title');assert.equal(card.image_url,api.defaults()[0].image_url);assert.equal(cards.at(-1).slot,1);});
test('reject unsafe links and image sources',()=>{const {api}=harness();for(const value of ['javascript:alert(1)','data:text/html,bad','https://user:secret@example.com','https://example.com\\evil'])assert.equal(api.safe(value),'');assert.equal(api.safe('//evil.com/a','image'),'');assert.ok(api.safe('https://example.com/a.jpg','image'));});
test('autoplay starts without play click, pauses, resumes and loops',async()=>{const h=harness();await h.api.initialize();assert.equal(h.track.children.length,13);assert.equal(h.controls['[data-carousel-position]'].textContent,'1, 2, 3 / 10');h.events.tick();assert.equal(h.track.style.transform,'translate3d(-320px,0,0)');h.events.reset();h.controls['[data-carousel-pause]'].onclick();h.events.tick();assert.equal(h.track.style.transform,'translate3d(-320px,0,0)');h.controls['[data-carousel-pause]'].onclick();for(let i=0;i<9;i++){h.events.tick();h.events.reset();}assert.equal(h.track.style.transform,'translate3d(0px,0,0)');});
test('mobile exposes one card and next control moves it',async()=>{const h=harness(390);await h.api.initialize();assert.equal(h.controls['[data-carousel-position]'].textContent,'1 / 10');h.controls['[data-carousel-next]'].onclick();assert.equal(h.controls['[data-carousel-position]'].textContent,'2 / 10');});
test('homepage queries exclude carousel placement before selecting banner',()=>{for(const file of ['js/main.js','js/admin.js'])assert.ok(fs.readFileSync(path.join(root,file),'utf8').includes('button_label=not.like.shop-carousel:*'));});
